insert into politieonderzoek_auto (nummerplaat, autotype, kleur, opmerkingen) values
('1-LAC-054','Opel Astra','Grijs','geen'),
('1-NKS-671','Mercedes C-Klasse','Zilver','geen'),
('1-VIV-579','BMW 3-serie', 'Blauw', 'geen'),
('1-BUK-565','Ford Focus','Groen','geen'),
('1-DVE-466','Volkswagen Golf','Blauw','geen'),
('2-CVP-047','Volvo XC40','Blauw','openstaande boete'),
('2-BZT-587','BMW 3-serie','Grijs','geen'),
('2-ADA-927','Audi A3','Beige','geen'),
('2-SUA-271','Volvo XC40','Geel','geen'),
('1-ZHT-758','Ford Focus','Grijs','verdacht voertuig ivm inbraak'),
('1-QGO-469','Mercedes C-Klasse','Geel','openstaande boete'),
('2-LUQ-602','Volkswagen Golf','Blauw','openstaande boete'),
('1-HLQ-278','Mercedes C-Klasse','Wit','geen'),
('2-EAO-846','Opel Astra','Zilver','geen'),
('2-NVT-833','Volvo XC40','Zilver','geen'),
('1-QRP-826','Opel Astra','Rood','in beslag genomen voor drugsfeiten'),
('2-WHZ-474','BMW 3-serie','Grijs','geen'),
('2-OHQ-198','Renault Clio','Beige','geen'),
('2-FYF-643','Audi A3','Bruin','geen'),
('2-UHA-635','Audi A3','Rood','verdacht voertuig vluchtmisdrijf'),
('2-OVE-820','Peugeot 208','Zwart','geen'),
('2-FAA-481','Mercedes C-Klasse','Groen','geen'),
('1-OYL-654','Volvo XC40','Beige','geen'),
('1-CDW-951','Peugeot 208','Zilver','geen'),
('1-TJW-764','Peugeot 208','Beige','geen'),
('2-TVY-183','Peugeot Expert','wit','in beslag genomen voor drugsfeiten'),
('1-NTW-377','Opel Astra','Wit','geen'),
('1-TGX-867','Ford Focus','Wit','geen'),
('2-NLA-282','Mercedes C-Klasse','Geel','geen');
