# Generated by Django 5.2.4 on 2025-07-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummerplaat', models.CharField(unique=True)),
                ('autotype', models.CharField()),
                ('kleur', models.CharField()),
                ('opmerkingen', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField()),
                ('familienaam', models.CharField()),
                ('beroep', models.CharField()),
                ('opmerkingen', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politieterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afkorting', models.CharField(unique=True)),
                ('betekenis', models.CharField()),
                ('uitleg', models.CharField(blank=True)),
            ],
        ),
    ]
