# Generated by Django 5.2.4 on 2025-07-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politieonderzoek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persoon',
            name='geboortedatum',
            field=models.CharField(default='00/00/0000'),
        ),
    ]
